name: Testing

on:
  push:
    branches: [ testing ]
  workflow_dispatch:

permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: install jpeg
      run: brew install jpeg libtiff

    - name: get jpeg
      run: ls /usr/local/opt

    - name: jpeg
      run: ls /usr/local/opt/jpeg/lib
   
    - name: jpeg-turbo
      run: ls /usr/local/opt/jpeg-turbo/lib

    - name: jpeg-xl
      run: ls /usr/local/opt/jpeg-xl/lib

    - name: libjpeg-turbo
      run: ls /usr/local/opt/libjpeg-turbo/lib

    - name: openjpeg
      run: ls /usr/local/opt/openjpeg/lib